#!/bin/bash
echo "filename: "
read filename
echo '#include <stdio.h>
/**
 * main - Entry point
 *
 * Return: Always 0 (Success)
 */
int main(void)
{
    printf("Hello, world!\n");
    return (0);
}' > ${filename}
vi ${filename}
